name: CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: KinD (Kubernetes in Docker) Action
      uses: engineerd/setup-kind@v0.1.0
      with:
        version: v0.6.1
    - name: Check Kube status
      run: kubectl get pod
